[phases.setup]
aptPkgs = ["libicu-dev", "libzip-dev", "zlib1g-dev"]

[phases.extensions]
cmds = [
    "install-php-extensions intl zip ctype curl dom fileinfo filter hash mbstring openssl pcre pdo session tokenizer xml"
]

[phases.install]
dependsOn = ["extensions"]
cmds = [
    "composer install --optimize-autoloader --no-scripts --no-interaction"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "npm ci",
    "npm run build",
    "mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache",
    "chmod -R a+rw storage",
    "php artisan config:cache",
    "php artisan event:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]
