[phases.setup]
aptPkgs = ["libicu-dev", "libzip-dev"]

[phases.install]
cmds = [
    "install-php-extensions intl zip",
    "composer install --optimize-autoloader --no-scripts --no-interaction"
]

[phases.build]
cmds = [
    "npm ci",
    "npm run build",
    "mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache",
    "chmod -R a+rw storage",
    "php artisan config:cache",
    "php artisan event:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]
